using ClashWinUI.Models;
using ClashWinUI.Services.Interfaces;
using System;

namespace ClashWinUI.Helpers
{
    internal static class TunRuntimeDiagnosticHelper
    {
        internal static readonly TimeSpan DefaultTunDiagnosticFreshnessWindow = TimeSpan.FromSeconds(30);

        internal static TunRuntimeStatus ApplyPreferredKernelDiagnostic(
            IProcessService processService,
            TunRuntimeStatus runtimeStatus,
            TimeSpan? freshnessWindow = null)
        {
            ArgumentNullException.ThrowIfNull(processService);
            ArgumentNullException.ThrowIfNull(runtimeStatus);

            if (runtimeStatus.IsHealthy || !MihomoFailureKindHelper.IsTunFailure(runtimeStatus.FailureKind))
            {
                return Clone(runtimeStatus);
            }

            MihomoFailureDiagnostic diagnostic = ResolvePreferredTunDiagnostic(
                processService,
                freshnessWindow ?? DefaultTunDiagnosticFreshnessWindow);
            if (!MihomoFailureKindHelper.IsTunFailure(diagnostic.Kind)
                || string.IsNullOrWhiteSpace(diagnostic.Message))
            {
                return Clone(runtimeStatus);
            }

            MihomoFailureKind runtimeKind = runtimeStatus.FailureKind == MihomoFailureKind.None
                ? MihomoFailureKind.TunRouteMissing
                : runtimeStatus.FailureKind;
            string runtimeMessage = string.IsNullOrWhiteSpace(runtimeStatus.Message)
                ? "TUN runtime validation failed."
                : runtimeStatus.Message.Trim();
            string diagnosticMessage = diagnostic.Message.Trim();

            if (runtimeKind == diagnostic.Kind)
            {
                return Clone(runtimeStatus, runtimeKind, MergeDistinctMessages(diagnosticMessage, runtimeMessage));
            }

            if (runtimeKind == MihomoFailureKind.TunRouteMissing && diagnostic.Kind != MihomoFailureKind.TunRouteMissing)
            {
                return Clone(runtimeStatus, diagnostic.Kind, MergeDistinctMessages(diagnosticMessage, runtimeMessage));
            }

            return Clone(runtimeStatus, runtimeKind, runtimeMessage);
        }

        internal static MihomoFailureDiagnostic ResolvePreferredTunDiagnostic(
            IProcessService processService,
            TimeSpan freshnessWindow)
        {
            ArgumentNullException.ThrowIfNull(processService);

            if (processService is Services.Implementations.ProcessService concreteProcessService
                && concreteProcessService.TryGetRecentTunFailureDiagnostic(freshnessWindow, out MihomoFailureDiagnostic preferredDiagnostic))
            {
                return preferredDiagnostic;
            }

            MihomoFailureDiagnostic diagnostic = processService.LastFailureDiagnostic;
            if (MihomoFailureKindHelper.IsTunFailure(diagnostic.Kind)
                && !string.IsNullOrWhiteSpace(diagnostic.Message)
                && diagnostic.OccurredAt >= DateTimeOffset.UtcNow - freshnessWindow)
            {
                return diagnostic;
            }

            return MihomoFailureDiagnostic.None;
        }

        internal static TunRuntimeStatus Clone(
            TunRuntimeStatus status,
            MihomoFailureKind? failureKind = null,
            string? message = null)
        {
            ArgumentNullException.ThrowIfNull(status);

            return new TunRuntimeStatus
            {
                IsConfigured = status.IsConfigured,
                IsHealthy = status.IsHealthy,
                DriverLoaded = status.DriverLoaded,
                DriverVersion = status.DriverVersion,
                AdapterPresent = status.AdapterPresent,
                AdapterName = status.AdapterName,
                RouteAttached = status.RouteAttached,
                EffectiveStack = status.EffectiveStack,
                FirewallEnabled = status.FirewallEnabled,
                DnsHijackConfigured = status.DnsHijackConfigured,
                DnsManaged = status.DnsManaged,
                DnsAutoGenerated = status.DnsAutoGenerated,
                FailureKind = failureKind ?? status.FailureKind,
                Message = message ?? status.Message,
            };
        }

        internal static string MergeDistinctMessages(string primary, string secondary)
        {
            string normalizedPrimary = primary?.Trim() ?? string.Empty;
            string normalizedSecondary = secondary?.Trim() ?? string.Empty;

            if (string.IsNullOrWhiteSpace(normalizedPrimary))
            {
                return normalizedSecondary;
            }

            if (string.IsNullOrWhiteSpace(normalizedSecondary))
            {
                return normalizedPrimary;
            }

            if (normalizedPrimary.Equals(normalizedSecondary, StringComparison.OrdinalIgnoreCase)
                || normalizedPrimary.Contains(normalizedSecondary, StringComparison.OrdinalIgnoreCase))
            {
                return normalizedPrimary;
            }

            if (normalizedSecondary.Contains(normalizedPrimary, StringComparison.OrdinalIgnoreCase))
            {
                return normalizedSecondary;
            }

            return $"{normalizedPrimary} {normalizedSecondary}";
        }
    }
}
