using ClashWinUI.Models;
using ClashWinUI.Services.Interfaces;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace ClashWinUI.Helpers
{
    internal static class TunRuntimeValidationHelper
    {
        private static readonly TimeSpan TunConvergenceTimeout = TimeSpan.FromSeconds(8);
        private static readonly TimeSpan TunConvergencePollDelay = TimeSpan.FromMilliseconds(250);

        public static async Task<TunRuntimeValidationOutcome> ValidateAsync(
            ITunService tunService,
            IKernelPathService kernelPathService,
            IProcessService processService,
            string configPath,
            CancellationToken cancellationToken = default)
        {
            ArgumentNullException.ThrowIfNull(tunService);
            ArgumentNullException.ThrowIfNull(kernelPathService);
            ArgumentNullException.ThrowIfNull(processService);

            if (!tunService.IsTunEnabled(configPath))
            {
                return TunRuntimeValidationOutcome.Passed(TunRuntimeStatus.Disabled());
            }

            DateTimeOffset deadline = DateTimeOffset.UtcNow.Add(TunConvergenceTimeout);
            TunRuntimeStatus runtimeStatus = ReadRuntimeStatusSafe(tunService, kernelPathService, configPath);

            while (!runtimeStatus.IsHealthy && DateTimeOffset.UtcNow < deadline)
            {
                await Task.Delay(TunConvergencePollDelay, cancellationToken).ConfigureAwait(false);
                runtimeStatus = ReadRuntimeStatusSafe(tunService, kernelPathService, configPath);
            }

            if (runtimeStatus.IsHealthy)
            {
                return TunRuntimeValidationOutcome.Passed(runtimeStatus);
            }

            return BuildFailureOutcome(processService, runtimeStatus);
        }

        private static TunRuntimeValidationOutcome BuildFailureOutcome(
            IProcessService processService,
            TunRuntimeStatus runtimeStatus)
        {
            TunRuntimeStatus decoratedRuntimeStatus = TunRuntimeDiagnosticHelper.ApplyPreferredKernelDiagnostic(processService, runtimeStatus);
            MihomoFailureKind runtimeKind = decoratedRuntimeStatus.FailureKind == MihomoFailureKind.None
                ? MihomoFailureKind.TunRouteMissing
                : decoratedRuntimeStatus.FailureKind;
            string runtimeMessage = string.IsNullOrWhiteSpace(decoratedRuntimeStatus.Message)
                ? "TUN runtime validation failed."
                : decoratedRuntimeStatus.Message.Trim();

            return TunRuntimeValidationOutcome.Failed(decoratedRuntimeStatus, runtimeKind, runtimeMessage);
        }

        private static TunRuntimeStatus ReadRuntimeStatusSafe(
            ITunService tunService,
            IKernelPathService kernelPathService,
            string configPath)
        {
            try
            {
                return tunService.GetRuntimeStatus(configPath, kernelPathService.ResolveKernelPath());
            }
            catch (Exception ex)
            {
                return new TunRuntimeStatus
                {
                    IsConfigured = true,
                    IsHealthy = false,
                    DriverLoaded = false,
                    DriverVersion = string.Empty,
                    AdapterPresent = false,
                    AdapterName = string.Empty,
                    RouteAttached = false,
                    EffectiveStack = string.Empty,
                    FirewallEnabled = WindowsFirewallHelper.IsAnyProfileEnabled(),
                    DnsHijackConfigured = false,
                    DnsManaged = false,
                    DnsAutoGenerated = false,
                    FailureKind = MihomoFailureKind.TunDependency,
                    Message = ex.Message,
                };
            }
        }
    }

    internal readonly record struct TunRuntimeValidationOutcome(
        bool Success,
        TunRuntimeStatus RuntimeStatus,
        MihomoFailureKind FailureKind,
        string Message)
    {
        public static TunRuntimeValidationOutcome Passed(TunRuntimeStatus runtimeStatus) =>
            new(true, runtimeStatus, MihomoFailureKind.None, string.Empty);

        public static TunRuntimeValidationOutcome Failed(
            TunRuntimeStatus runtimeStatus,
            MihomoFailureKind failureKind,
            string message) =>
            new(false, runtimeStatus, failureKind, message);
    }
}
