using ClashWinUI.Helpers;
using ClashWinUI.Models;
using ClashWinUI.Services.Implementations.Native;
using ClashWinUI.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.IO;
using System.Diagnostics;
using System.Linq;
using System.Management;
using System.Net.NetworkInformation;
using System.Runtime.InteropServices;
using YamlDotNet.RepresentationModel;

namespace ClashWinUI.Services.Implementations
{
    public sealed class TunService : ITunService
    {
        private const string WintunFileName = "wintun.dll";
        private const string DefaultAdapterName = "Mihomo";
        private static readonly TimeSpan ThirdPartyConflictCacheDuration = TimeSpan.FromSeconds(5);

        private readonly IAppLogService _logService;
        private readonly object _diagnosticGate = new();
        private readonly object _thirdPartyConflictGate = new();
        private string _lastRuntimeDiagnosticFingerprint = string.Empty;
        private DateTimeOffset _lastThirdPartyConflictRefresh = DateTimeOffset.MinValue;
        private IReadOnlyList<string> _cachedThirdPartyConflictHints = Array.Empty<string>();

        public TunService(IAppLogService logService)
        {
            _logService = logService ?? throw new ArgumentNullException(nameof(logService));
        }

        public bool IsTunEnabled(string configPath)
        {
            try
            {
                return LoadTunConfigSnapshot(configPath).IsEnabled;
            }
            catch
            {
                return false;
            }
        }

        public TunRuntimeStatus GetRuntimeStatus(string configPath, string kernelExecutablePath)
        {
            TunConfigSnapshot snapshot;
            try
            {
                snapshot = LoadTunConfigSnapshot(configPath);
            }
            catch (Exception ex)
            {
                return new TunRuntimeStatus
                {
                    IsConfigured = true,
                    IsHealthy = false,
                    DriverLoaded = false,
                    DriverVersion = string.Empty,
                    AdapterPresent = false,
                    AdapterName = string.Empty,
                    RouteAttached = false,
                    EffectiveStack = string.Empty,
                    FirewallEnabled = WindowsFirewallHelper.IsAnyProfileEnabled(),
                    DnsHijackConfigured = false,
                    DnsManaged = false,
                    DnsAutoGenerated = false,
                    FailureKind = MihomoFailureKind.TunDependency,
                    Message = ex.Message,
                };
            }

            if (!snapshot.IsEnabled)
            {
                ResetRuntimeDiagnostics();
                return TunRuntimeStatus.Disabled();
            }

            bool firewallEnabled = WindowsFirewallHelper.IsAnyProfileEnabled();
            if (!AppElevationHelper.IsProcessElevated())
            {
                return CreateRuntimeStatus(snapshot, false, string.Empty, false, false, firewallEnabled, MihomoFailureKind.TunPermission, "Current process is not running as administrator.");
            }

            TunPreparationResult preparation = EnsureWintunReady(kernelExecutablePath);
            if (!preparation.Success)
            {
                return CreateRuntimeStatus(snapshot, false, string.Empty, false, false, firewallEnabled, preparation.FailureKind, preparation.Message);
            }

            string wintunPath = ResolveWintunTargetPath(kernelExecutablePath);

            try
            {
                using var native = WintunNative.Load(wintunPath);
                uint driverVersionRaw = native.GetRunningDriverVersion();
                bool driverLoaded = driverVersionRaw != 0;
                string driverVersion = FormatDriverVersion(driverVersionRaw);

                using AdapterDiscoveryResult discovery = DiscoverRuntimeAdapter(native, snapshot);
                TunAdapterSnapshot selectedAdapter = ResolveSelectedAdapterSnapshot(snapshot, discovery);
                snapshot = snapshot with { DeviceName = ResolveRuntimeAdapterName(snapshot, selectedAdapter, discovery.AdapterHandle?.Name) };
                string conflictDetail = BuildConflictDetail(snapshot, discovery);

                if (!discovery.TargetAdapterPresent)
                {
                    TunRuntimeStatus status = CreateRuntimeStatus(
                        snapshot,
                        driverLoaded,
                        driverVersion,
                        false,
                        false,
                        firewallEnabled,
                        MihomoFailureKind.TunAdapterMissing,
                        BuildRuntimeMessage(snapshot, selectedAdapter, RouteInspectionResult.Empty, MihomoFailureKind.TunAdapterMissing, conflictDetail));
                    LogRuntimeDiagnosticsIfChanged(snapshot, discovery, selectedAdapter, null, 0, RouteInspectionResult.Empty, status);
                    return status;
                }

                if (discovery.AdapterHandle is not null && !driverLoaded)
                {
                    driverVersionRaw = native.GetRunningDriverVersion();
                    driverLoaded = driverVersionRaw != 0;
                    driverVersion = FormatDriverVersion(driverVersionRaw);
                }

                if (!driverLoaded)
                {
                    TunRuntimeStatus dependencyStatus = CreateRuntimeStatus(
                        snapshot,
                        false,
                        driverVersion,
                        true,
                        false,
                        firewallEnabled,
                        MihomoFailureKind.TunDependency,
                        AppendDetail("Wintun driver is not reporting a running version.", conflictDetail));
                    LogRuntimeDiagnosticsIfChanged(snapshot, discovery, selectedAdapter, null, selectedAdapter.InterfaceIndex, RouteInspectionResult.Empty, dependencyStatus);
                    return dependencyStatus;
                }

                ulong? adapterLuid = null;
                string luidLookupError = string.Empty;
                if (discovery.AdapterHandle is not null)
                {
                    try
                    {
                        adapterLuid = discovery.AdapterHandle.GetLuid();
                    }
                    catch (Exception ex)
                    {
                        luidLookupError = $"Adapter LUID lookup failed: {NormalizeScalar(ex.Message)}";
                    }
                }

                uint interfaceIndex = selectedAdapter.InterfaceIndex;
                if (interfaceIndex == 0 && adapterLuid.HasValue && IpHelperNative.TryConvertInterfaceLuidToIndex(adapterLuid.Value, out uint convertedIndex, out _))
                {
                    interfaceIndex = convertedIndex;
                    selectedAdapter = selectedAdapter with { InterfaceIndex = convertedIndex };
                }

                RouteInspectionResult routeInspection = InspectRouteAttachment(
                    snapshot,
                    discovery,
                    selectedAdapter,
                    adapterLuid,
                    interfaceIndex);
                if (!routeInspection.IpHelperReadSucceeded)
                {
                    TunRuntimeStatus inspectionFailureStatus = CreateRuntimeStatus(
                        snapshot,
                        driverLoaded,
                        driverVersion,
                        adapterPresent: true,
                        routeAttached: false,
                        firewallEnabled,
                        MihomoFailureKind.TunDependency,
                        IpHelperNative.RuntimeInspectionFailureMessage);

                    LogRuntimeDiagnosticsIfChanged(
                        snapshot,
                        discovery,
                        selectedAdapter,
                        adapterLuid,
                        interfaceIndex,
                        routeInspection,
                        inspectionFailureStatus);

                    return inspectionFailureStatus;
                }

                if (routeInspection.RouteAttached)
                {
                    routeInspection = routeInspection with { HasIpInterface = true };
                }

                MihomoFailureKind failureKind = routeInspection.RouteAttached
                    ? snapshot.DnsManaged
                        ? MihomoFailureKind.None
                        : MihomoFailureKind.TunDnsUnmanaged
                    : routeInspection.HasIpInterface
                        && !routeInspection.HasAnyForeignTunDefaultRoute
                        && firewallEnabled
                        && IsFirewallSensitiveStack(snapshot.EffectiveStack)
                        ? MihomoFailureKind.TunFirewallBlocked
                        : MihomoFailureKind.TunRouteMissing;

                string detail = CombineDetails(
                    !selectedAdapter.CanOpenByWintunApi && !string.IsNullOrWhiteSpace(selectedAdapter.OpenError)
                        ? $"Wintun API open failed: {selectedAdapter.OpenError}"
                        : string.Empty,
                    luidLookupError,
                    routeInspection.Detail,
                    conflictDetail);

                TunRuntimeStatus runtimeStatus = CreateRuntimeStatus(
                    snapshot,
                    driverLoaded,
                    driverVersion,
                    true,
                    routeInspection.RouteAttached,
                    firewallEnabled,
                    failureKind,
                    BuildRuntimeMessage(snapshot, selectedAdapter, routeInspection, failureKind, detail));

                if (runtimeStatus.IsHealthy)
                {
                    ResetRuntimeDiagnostics();
                }
                else
                {
                    LogRuntimeDiagnosticsIfChanged(snapshot, discovery, selectedAdapter, adapterLuid, interfaceIndex, routeInspection, runtimeStatus);
                }

                return runtimeStatus;
            }
            catch (UnauthorizedAccessException ex)
            {
                return CreateRuntimeStatus(snapshot, false, string.Empty, false, false, firewallEnabled, MihomoFailureKind.TunPermission, ex.Message);
            }
            catch (FileNotFoundException ex)
            {
                return CreateRuntimeStatus(snapshot, false, string.Empty, false, false, firewallEnabled, MihomoFailureKind.TunDependency, ex.Message);
            }
            catch (EntryPointNotFoundException ex)
            {
                return CreateRuntimeStatus(snapshot, false, string.Empty, false, false, firewallEnabled, MihomoFailureKind.TunDependency, ex.Message);
            }
            catch (DllNotFoundException ex)
            {
                return CreateRuntimeStatus(snapshot, false, string.Empty, false, false, firewallEnabled, MihomoFailureKind.TunDependency, ex.Message);
            }
            catch (Exception ex)
            {
                return CreateRuntimeStatus(snapshot, false, string.Empty, false, false, firewallEnabled, MihomoFailureKind.TunDependency, ex.Message);
            }
        }

        public TunPreparationResult EnsureWintunReady(string kernelExecutablePath)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(kernelExecutablePath))
                {
                    return CreateFailure(MihomoFailureKind.TunDependency, "Kernel executable path is empty.");
                }

                string sourcePath = ResolveWintunSourcePath();
                if (!File.Exists(sourcePath))
                {
                    return CreateFailure(MihomoFailureKind.TunDependency, $"Wintun resource missing for {RuntimeInformation.ProcessArchitecture.ToString().ToUpperInvariant()}: {sourcePath}");
                }

                string targetDirectory = Path.GetDirectoryName(Path.GetFullPath(kernelExecutablePath)) ?? string.Empty;
                if (string.IsNullOrWhiteSpace(targetDirectory) || !Directory.Exists(targetDirectory))
                {
                    return CreateFailure(MihomoFailureKind.TunDependency, $"Kernel directory not found: {targetDirectory}");
                }

                string targetPath = Path.Combine(targetDirectory, WintunFileName);
                long sourceLength = new FileInfo(sourcePath).Length;
                if (File.Exists(targetPath) && new FileInfo(targetPath).Length == sourceLength)
                {
                    return TunPreparationResult.Ok();
                }

                File.Copy(sourcePath, targetPath, overwrite: true);
                return TunPreparationResult.Ok();
            }
            catch (UnauthorizedAccessException ex)
            {
                return CreateFailure(MihomoFailureKind.TunPermission, ex.Message);
            }
            catch (Exception ex)
            {
                return CreateFailure(MihomoFailureKind.TunDependency, ex.Message);
            }
        }

        public TunPreparationResult ValidateEnvironment(string kernelExecutablePath)
        {
            try
            {
                if (!AppElevationHelper.IsProcessElevated())
                {
                    return CreateFailure(MihomoFailureKind.TunPermission, "Current process is not running as administrator.");
                }

                return EnsureWintunReady(kernelExecutablePath);
            }
            catch (UnauthorizedAccessException ex)
            {
                return CreateFailure(MihomoFailureKind.TunPermission, ex.Message);
            }
            catch (Exception ex)
            {
                return CreateFailure(MihomoFailureKind.TunDependency, ex.Message);
            }
        }

        private static TunConfigSnapshot LoadTunConfigSnapshot(string configPath)
        {
            if (string.IsNullOrWhiteSpace(configPath) || !File.Exists(configPath))
            {
                return TunConfigSnapshot.Disabled;
            }

            var stream = new YamlStream();
            using var reader = new StringReader(File.ReadAllText(configPath));
            stream.Load(reader);
            if (stream.Documents.Count == 0 || stream.Documents[0].RootNode is not YamlMappingNode root)
            {
                return TunConfigSnapshot.Disabled;
            }

            if (!TryGetChild(root, "tun", out YamlNode? tunNode))
            {
                return TunConfigSnapshot.Disabled;
            }

            return tunNode switch
            {
                YamlMappingNode tunMapping => new TunConfigSnapshot(
                    GetBool(tunMapping, "enable"),
                    NormalizeScalar(GetString(tunMapping, "stack")),
                    NormalizeScalar(GetString(tunMapping, "device")),
                    HasValue(tunMapping, "dns-hijack"),
                    GetDnsEnabled(root),
                    HasDnsListen(root),
                    HasDnsNameserver(root),
                    IsDnsAutoGenerated(configPath)),
                YamlScalarNode scalar when bool.TryParse(scalar.Value, out bool enabled) => new TunConfigSnapshot(
                    enabled,
                    string.Empty,
                    string.Empty,
                    false,
                    GetDnsEnabled(root),
                    HasDnsListen(root),
                    HasDnsNameserver(root),
                    IsDnsAutoGenerated(configPath)),
                _ => TunConfigSnapshot.Disabled,
            };
        }

        private static TunRuntimeStatus CreateRuntimeStatus(
            TunConfigSnapshot snapshot,
            bool driverLoaded,
            string driverVersion,
            bool adapterPresent,
            bool routeAttached,
            bool firewallEnabled,
            MihomoFailureKind failureKind,
            string message)
        {
            bool isHealthy = snapshot.IsEnabled && driverLoaded && adapterPresent && routeAttached && snapshot.DnsManaged;
            return new TunRuntimeStatus
            {
                IsConfigured = snapshot.IsEnabled,
                IsHealthy = isHealthy,
                DriverLoaded = driverLoaded,
                DriverVersion = driverVersion,
                AdapterPresent = adapterPresent,
                AdapterName = snapshot.DeviceName,
                RouteAttached = routeAttached,
                EffectiveStack = snapshot.EffectiveStack,
                FirewallEnabled = firewallEnabled,
                DnsHijackConfigured = snapshot.DnsHijackConfigured,
                DnsManaged = snapshot.DnsManaged,
                DnsAutoGenerated = snapshot.DnsAutoGenerated,
                FailureKind = failureKind,
                Message = message.Trim(),
            };
        }

        private AdapterDiscoveryResult DiscoverRuntimeAdapter(WintunNative native, TunConfigSnapshot snapshot)
        {
            var attemptedNames = new List<string>();
            var adapterSnapshots = new List<TunAdapterSnapshot>();
            string firstOpenError = string.Empty;
            string configuredDeviceName = NormalizeScalar(snapshot.DeviceName);

            if (!string.IsNullOrWhiteSpace(configuredDeviceName))
            {
                if (TryOpenNamedCandidate(native, configuredDeviceName, configuredDeviceName, configuredDeviceName, 0, "ConfiguredName", attemptedNames, ref firstOpenError, out WintunNative.AdapterHandle? configuredAdapter, out TunAdapterSnapshot configuredSnapshot))
                {
                    return new AdapterDiscoveryResult(
                        configuredDeviceName,
                        configuredAdapter,
                        configuredSnapshot,
                        attemptedNames.ToArray(),
                        new[] { configuredSnapshot },
                        firstOpenError);
                }

                CollectDiscoveredAdapterSnapshots(adapterSnapshots);
                foreach (TunAdapterSnapshot candidate in GetOrderedMatchingCandidates(adapterSnapshots, configuredDeviceName))
                {
                    if (TryOpenDiscoveredCandidate(native, candidate, attemptedNames, ref firstOpenError, out WintunNative.AdapterHandle? openedAdapter, out TunAdapterSnapshot openedSnapshot))
                    {
                        UpsertAdapterSnapshot(adapterSnapshots, openedSnapshot);
                        return new AdapterDiscoveryResult(
                            configuredDeviceName,
                            openedAdapter,
                            openedSnapshot,
                            attemptedNames.ToArray(),
                            adapterSnapshots.ToArray(),
                            firstOpenError);
                    }

                    UpsertAdapterSnapshot(adapterSnapshots, openedSnapshot);
                }

                TunAdapterSnapshot selectedConfiguredSnapshot = SelectConfiguredAdapterSnapshot(adapterSnapshots, configuredDeviceName);
                if (selectedConfiguredSnapshot == TunAdapterSnapshot.Empty)
                {
                    selectedConfiguredSnapshot = new TunAdapterSnapshot(
                        configuredDeviceName,
                        string.Empty,
                        configuredDeviceName,
                        0,
                        false,
                        false,
                        firstOpenError,
                        "ConfiguredName");
                }

                return new AdapterDiscoveryResult(
                    configuredDeviceName,
                    null,
                    selectedConfiguredSnapshot,
                    attemptedNames.ToArray(),
                    adapterSnapshots.ToArray(),
                    firstOpenError);
            }

            if (TryOpenNamedCandidate(native, DefaultAdapterName, DefaultAdapterName, string.Empty, 0, "DefaultName", attemptedNames, ref firstOpenError, out WintunNative.AdapterHandle? defaultAdapter, out TunAdapterSnapshot defaultSnapshot))
            {
                return new AdapterDiscoveryResult(string.Empty, defaultAdapter, defaultSnapshot, attemptedNames.ToArray(), new[] { defaultSnapshot }, firstOpenError);
            }

            foreach (TunAdapterSnapshot candidate in EnumerateWmiAdapterSnapshots())
            {
                UpsertAdapterSnapshot(adapterSnapshots, candidate);
                if (TryOpenDiscoveredCandidate(native, candidate, attemptedNames, ref firstOpenError, out WintunNative.AdapterHandle? openedAdapter, out TunAdapterSnapshot openedSnapshot))
                {
                    UpsertAdapterSnapshot(adapterSnapshots, openedSnapshot);
                    return new AdapterDiscoveryResult(string.Empty, openedAdapter, openedSnapshot, attemptedNames.ToArray(), adapterSnapshots.ToArray(), firstOpenError);
                }

                UpsertAdapterSnapshot(adapterSnapshots, openedSnapshot);
            }

            foreach (TunAdapterSnapshot candidate in EnumerateNetworkInterfaceSnapshots())
            {
                UpsertAdapterSnapshot(adapterSnapshots, candidate);
                if (TryOpenDiscoveredCandidate(native, candidate, attemptedNames, ref firstOpenError, out WintunNative.AdapterHandle? openedAdapter, out TunAdapterSnapshot openedSnapshot))
                {
                    UpsertAdapterSnapshot(adapterSnapshots, openedSnapshot);
                    return new AdapterDiscoveryResult(string.Empty, openedAdapter, openedSnapshot, attemptedNames.ToArray(), adapterSnapshots.ToArray(), firstOpenError);
                }

                UpsertAdapterSnapshot(adapterSnapshots, openedSnapshot);
            }

            return new AdapterDiscoveryResult(
                string.Empty,
                null,
                SelectBestAdapterSnapshot(adapterSnapshots),
                attemptedNames.ToArray(),
                adapterSnapshots.ToArray(),
                firstOpenError);
        }

        private static void CollectDiscoveredAdapterSnapshots(List<TunAdapterSnapshot> adapterSnapshots)
        {
            foreach (TunAdapterSnapshot candidate in EnumerateWmiAdapterSnapshots())
            {
                UpsertAdapterSnapshot(adapterSnapshots, candidate);
            }

            foreach (TunAdapterSnapshot candidate in EnumerateNetworkInterfaceSnapshots())
            {
                UpsertAdapterSnapshot(adapterSnapshots, candidate);
            }
        }

        private static IReadOnlyList<TunAdapterSnapshot> GetOrderedMatchingCandidates(
            IReadOnlyList<TunAdapterSnapshot> snapshots,
            string configuredDeviceName)
        {
            string normalizedConfiguredName = NormalizeScalar(configuredDeviceName);
            if (string.IsNullOrWhiteSpace(normalizedConfiguredName))
            {
                return Array.Empty<TunAdapterSnapshot>();
            }

            return snapshots
                .Where(snapshot => MatchesConfiguredName(snapshot, normalizedConfiguredName))
                .OrderByDescending(snapshot => snapshot.CanOpenByWintunApi)
                .ThenByDescending(snapshot => snapshot.InterfaceIndex != 0)
                .ThenByDescending(snapshot => snapshot.AdapterPresent)
                .ThenBy(snapshot => GetDiscoveryRank(snapshot.DiscoverySource))
                .ToArray();
        }

        private static bool TryOpenNamedCandidate(
            WintunNative native,
            string candidateName,
            string displayName,
            string netConnectionId,
            uint interfaceIndex,
            string discoverySource,
            List<string> attemptedNames,
            ref string firstOpenError,
            out WintunNative.AdapterHandle? adapterHandle,
            out TunAdapterSnapshot adapterSnapshot)
        {
            adapterHandle = null;
            adapterSnapshot = TunAdapterSnapshot.Empty;

            string normalizedCandidate = NormalizeScalar(candidateName);
            if (string.IsNullOrWhiteSpace(normalizedCandidate))
            {
                return false;
            }

            AddAttemptedName(attemptedNames, normalizedCandidate);
            if (!native.TryOpenAdapter(normalizedCandidate, out adapterHandle, out string? openError))
            {
                TrySetFirstDetail(ref firstOpenError, NormalizeScalar(openError));
                return false;
            }

            adapterSnapshot = new TunAdapterSnapshot(
                string.IsNullOrWhiteSpace(displayName) ? normalizedCandidate : NormalizeScalar(displayName),
                string.Empty,
                NormalizeScalar(netConnectionId),
                interfaceIndex,
                true,
                true,
                string.Empty,
                discoverySource);
            return true;
        }

        private static bool TryOpenDiscoveredCandidate(
            WintunNative native,
            TunAdapterSnapshot candidate,
            List<string> attemptedNames,
            ref string firstOpenError,
            out WintunNative.AdapterHandle? adapterHandle,
            out TunAdapterSnapshot openedSnapshot)
        {
            adapterHandle = null;
            string candidateOpenError = string.Empty;

            foreach (string openName in EnumerateCandidateOpenNames(candidate))
            {
                AddAttemptedName(attemptedNames, openName);
                if (native.TryOpenAdapter(openName, out adapterHandle, out string? openError))
                {
                    openedSnapshot = candidate with
                    {
                        CanOpenByWintunApi = true,
                        OpenError = string.Empty,
                    };
                    return true;
                }

                TrySetFirstDetail(ref candidateOpenError, NormalizeScalar(openError));
                TrySetFirstDetail(ref firstOpenError, NormalizeScalar(openError));
            }

            openedSnapshot = candidate with
            {
                CanOpenByWintunApi = false,
                OpenError = candidateOpenError,
            };
            return false;
        }

        private static IReadOnlyList<string> EnumerateCandidateOpenNames(TunAdapterSnapshot candidate)
        {
            return new[]
            {
                candidate.NetConnectionId,
                candidate.DisplayName,
                candidate.Description,
            }
                .Where(name => !string.IsNullOrWhiteSpace(name))
                .Select(NormalizeScalar)
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToArray();
        }

        private static IReadOnlyList<TunAdapterSnapshot> EnumerateWmiAdapterSnapshots()
        {
            var snapshots = new List<TunAdapterSnapshot>();

            try
            {
                using var searcher = new ManagementObjectSearcher("SELECT Name, Description, NetConnectionID, InterfaceIndex FROM Win32_NetworkAdapter");
                using ManagementObjectCollection results = searcher.Get();

                foreach (ManagementBaseObject result in results)
                {
                    string name = NormalizeScalar(result["Name"] as string);
                    string description = NormalizeScalar(result["Description"] as string);
                    string netConnectionId = NormalizeScalar(result["NetConnectionID"] as string);
                    uint interfaceIndex = ReadUInt32(result["InterfaceIndex"]);

                    if (!LooksLikeTunAdapter(name, description, netConnectionId))
                    {
                        continue;
                    }

                    string displayName = !string.IsNullOrWhiteSpace(name) ? name : description;
                    UpsertAdapterSnapshot(snapshots, new TunAdapterSnapshot(displayName, description, netConnectionId, interfaceIndex, true, false, string.Empty, "Win32_NetworkAdapter"));
                }
            }
            catch
            {
                // Best-effort discovery only.
            }

            return snapshots.ToArray();
        }

        private static IReadOnlyList<TunAdapterSnapshot> EnumerateNetworkInterfaceSnapshots()
        {
            var snapshots = new List<TunAdapterSnapshot>();

            try
            {
                foreach (NetworkInterface networkInterface in NetworkInterface.GetAllNetworkInterfaces())
                {
                    string name = NormalizeScalar(networkInterface.Name);
                    string description = NormalizeScalar(networkInterface.Description);
                    if (!LooksLikeTunAdapter(name, description, name))
                    {
                        continue;
                    }

                    uint interfaceIndex = 0;
                    try
                    {
                        interfaceIndex = (uint)(networkInterface.GetIPProperties().GetIPv4Properties()?.Index ?? 0);
                    }
                    catch
                    {
                        interfaceIndex = 0;
                    }

                    UpsertAdapterSnapshot(snapshots, new TunAdapterSnapshot(name, description, name, interfaceIndex, true, false, string.Empty, "NetworkInterface"));
                }
            }
            catch
            {
                // Supplemental discovery only.
            }

            return snapshots.ToArray();
        }

        private static void UpsertAdapterSnapshot(List<TunAdapterSnapshot> snapshots, TunAdapterSnapshot snapshot)
        {
            if (snapshot == TunAdapterSnapshot.Empty)
            {
                return;
            }

            int existingIndex = snapshots.FindIndex(existing => IsSameAdapter(existing, snapshot));
            if (existingIndex < 0)
            {
                snapshots.Add(snapshot);
                return;
            }

            TunAdapterSnapshot existing = snapshots[existingIndex];
            snapshots[existingIndex] = existing with
            {
                DisplayName = FirstNonEmpty(existing.DisplayName, snapshot.DisplayName),
                Description = FirstNonEmpty(existing.Description, snapshot.Description),
                NetConnectionId = FirstNonEmpty(existing.NetConnectionId, snapshot.NetConnectionId),
                InterfaceIndex = existing.InterfaceIndex != 0 ? existing.InterfaceIndex : snapshot.InterfaceIndex,
                AdapterPresent = existing.AdapterPresent || snapshot.AdapterPresent,
                CanOpenByWintunApi = existing.CanOpenByWintunApi || snapshot.CanOpenByWintunApi,
                OpenError = FirstNonEmpty(existing.OpenError, snapshot.OpenError),
                DiscoverySource = MergeDiscoverySource(existing.DiscoverySource, snapshot.DiscoverySource),
            };
        }

        private static bool IsSameAdapter(TunAdapterSnapshot left, TunAdapterSnapshot right)
        {
            if (left.InterfaceIndex != 0 && right.InterfaceIndex != 0 && left.InterfaceIndex == right.InterfaceIndex)
            {
                return true;
            }

            if (!string.IsNullOrWhiteSpace(left.NetConnectionId)
                && !string.IsNullOrWhiteSpace(right.NetConnectionId)
                && left.NetConnectionId.Equals(right.NetConnectionId, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            return !string.IsNullOrWhiteSpace(left.DisplayName)
                && !string.IsNullOrWhiteSpace(right.DisplayName)
                && left.DisplayName.Equals(right.DisplayName, StringComparison.OrdinalIgnoreCase);
        }

        private static TunAdapterSnapshot ResolveSelectedAdapterSnapshot(TunConfigSnapshot snapshot, AdapterDiscoveryResult discovery)
        {
            if (discovery.SelectedSnapshot != TunAdapterSnapshot.Empty)
            {
                return discovery.SelectedSnapshot;
            }

            if (discovery.AdapterHandle is null)
            {
                return new TunAdapterSnapshot(snapshot.DeviceName, string.Empty, string.Empty, 0, discovery.TargetAdapterPresent, false, discovery.PrimaryOpenError, "Unresolved");
            }

            string handleName = NormalizeScalar(discovery.AdapterHandle.Name);
            return new TunAdapterSnapshot(
                string.IsNullOrWhiteSpace(handleName) ? snapshot.DeviceName : handleName,
                string.Empty,
                handleName,
                0,
                true,
                true,
                string.Empty,
                "WintunApi");
        }

        private static TunAdapterSnapshot SelectConfiguredAdapterSnapshot(IReadOnlyList<TunAdapterSnapshot> snapshots, string configuredDeviceName)
        {
            string normalizedConfiguredName = NormalizeScalar(configuredDeviceName);
            if (string.IsNullOrWhiteSpace(normalizedConfiguredName))
            {
                return TunAdapterSnapshot.Empty;
            }

            return snapshots
                .Where(snapshot => MatchesConfiguredName(snapshot, normalizedConfiguredName))
                .OrderByDescending(snapshot => snapshot.CanOpenByWintunApi)
                .ThenByDescending(snapshot => snapshot.InterfaceIndex != 0)
                .ThenByDescending(snapshot => snapshot.AdapterPresent)
                .ThenBy(snapshot => GetDiscoveryRank(snapshot.DiscoverySource))
                .FirstOrDefault(TunAdapterSnapshot.Empty);
        }

        private static TunAdapterSnapshot SelectBestAdapterSnapshot(IReadOnlyList<TunAdapterSnapshot> snapshots)
        {
            if (snapshots.Count == 0)
            {
                return TunAdapterSnapshot.Empty;
            }

            return snapshots
                .OrderByDescending(snapshot => snapshot.CanOpenByWintunApi)
                .ThenByDescending(snapshot => snapshot.InterfaceIndex != 0)
                .ThenByDescending(snapshot => snapshot.AdapterPresent)
                .ThenBy(snapshot => GetDiscoveryRank(snapshot.DiscoverySource))
                .First();
        }

        private static bool MatchesConfiguredName(TunAdapterSnapshot snapshot, string configuredDeviceName)
        {
            if (string.IsNullOrWhiteSpace(configuredDeviceName))
            {
                return false;
            }

            return EnumerateCandidateOpenNames(snapshot).Any(name => name.Equals(configuredDeviceName, StringComparison.OrdinalIgnoreCase));
        }

        private static int GetDiscoveryRank(string discoverySource)
        {
            if (discoverySource.Contains("WintunApi", StringComparison.OrdinalIgnoreCase))
            {
                return 0;
            }

            if (discoverySource.Contains("Win32_NetworkAdapter", StringComparison.OrdinalIgnoreCase))
            {
                return 1;
            }

            if (discoverySource.Contains("NetworkInterface", StringComparison.OrdinalIgnoreCase))
            {
                return 2;
            }

            return 3;
        }

        private static string ResolveRuntimeAdapterName(
            TunConfigSnapshot snapshot,
            TunAdapterSnapshot selectedAdapter,
            string? openedAdapterName)
        {
            if (!string.IsNullOrWhiteSpace(snapshot.DeviceName))
            {
                return snapshot.DeviceName;
            }

            if (!string.IsNullOrWhiteSpace(selectedAdapter.NetConnectionId))
            {
                return selectedAdapter.NetConnectionId;
            }

            if (!string.IsNullOrWhiteSpace(selectedAdapter.DisplayName))
            {
                return selectedAdapter.DisplayName;
            }

            return NormalizeScalar(openedAdapterName);
        }

        private string BuildConflictDetail(TunConfigSnapshot snapshot, AdapterDiscoveryResult discovery)
        {
            var details = new List<string>();

            IReadOnlyList<TunAdapterSnapshot> foreignCandidates = GetForeignCandidateSnapshots(discovery.CandidateSnapshots, snapshot.DeviceName);
            if (foreignCandidates.Count > 0)
            {
                string candidateNames = string.Join(
                    ", ",
                    foreignCandidates
                        .Select(GetAdapterConflictLabel)
                        .Where(name => !string.IsNullOrWhiteSpace(name))
                        .Distinct(StringComparer.OrdinalIgnoreCase)
                        .Take(4));

                if (!string.IsNullOrWhiteSpace(candidateNames))
                {
                    details.Add(string.IsNullOrWhiteSpace(snapshot.DeviceName)
                        ? $"Detected other TUN-like adapters: {candidateNames}."
                        : $"Detected other TUN-like adapters that do not match '{snapshot.DeviceName}': {candidateNames}.");
                }
            }

            IReadOnlyList<string> thirdPartyConflictHints = GetThirdPartyTunConflictHints();
            if (thirdPartyConflictHints.Count > 0)
            {
                details.Add($"Detected third-party Clash TUN services/processes: {string.Join(", ", thirdPartyConflictHints)}.");
            }

            return string.Join(" ", details);
        }

        private IReadOnlyList<string> GetThirdPartyTunConflictHints()
        {
            DateTimeOffset now = DateTimeOffset.UtcNow;
            lock (_thirdPartyConflictGate)
            {
                if (now - _lastThirdPartyConflictRefresh < ThirdPartyConflictCacheDuration)
                {
                    return _cachedThirdPartyConflictHints;
                }
            }

            IReadOnlyList<string> detectedHints = DetectThirdPartyTunConflictHints();
            lock (_thirdPartyConflictGate)
            {
                _cachedThirdPartyConflictHints = detectedHints;
                _lastThirdPartyConflictRefresh = now;
                return _cachedThirdPartyConflictHints;
            }
        }

        private static IReadOnlyList<string> DetectThirdPartyTunConflictHints()
        {
            var hints = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            DetectThirdPartyConflictProcesses(hints);
            DetectThirdPartyConflictServices(hints);
            return hints
                .Where(hint => !string.IsNullOrWhiteSpace(hint))
                .Take(4)
                .ToArray();
        }

        private static void DetectThirdPartyConflictProcesses(HashSet<string> hints)
        {
            try
            {
                foreach (Process process in Process.GetProcesses())
                {
                    try
                    {
                        string processName = NormalizeScalar(process.ProcessName);
                        if (LooksLikeThirdPartyClashActor(processName))
                        {
                            hints.Add($"process '{processName}.exe'");
                        }
                    }
                    catch
                    {
                        // Best-effort detection only.
                    }
                    finally
                    {
                        process.Dispose();
                    }
                }
            }
            catch
            {
                // Best-effort detection only.
            }
        }

        private static void DetectThirdPartyConflictServices(HashSet<string> hints)
        {
            try
            {
                using var searcher = new ManagementObjectSearcher("SELECT Name, DisplayName, State, PathName FROM Win32_Service WHERE State = 'Running'");
                using ManagementObjectCollection results = searcher.Get();

                foreach (ManagementBaseObject result in results)
                {
                    string serviceName = NormalizeScalar(result["Name"] as string);
                    string displayName = NormalizeScalar(result["DisplayName"] as string);
                    string pathName = NormalizeScalar(result["PathName"] as string);
                    if (!LooksLikeThirdPartyClashActor(serviceName, displayName, pathName))
                    {
                        continue;
                    }

                    string label = !string.IsNullOrWhiteSpace(displayName) ? displayName : serviceName;
                    if (!string.IsNullOrWhiteSpace(label))
                    {
                        hints.Add($"service '{label}'");
                    }
                }
            }
            catch
            {
                // Best-effort detection only.
            }
        }

        private static bool LooksLikeThirdPartyClashActor(params string[] values)
        {
            string combined = string.Join(" ", values.Select(NormalizeScalar).Where(value => !string.IsNullOrWhiteSpace(value)));
            if (string.IsNullOrWhiteSpace(combined))
            {
                return false;
            }

            if (combined.Contains("clashwinui", StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            return combined.Contains("clash-verge", StringComparison.OrdinalIgnoreCase)
                || combined.Contains("clash_verge", StringComparison.OrdinalIgnoreCase)
                || combined.Contains("verge", StringComparison.OrdinalIgnoreCase)
                || combined.Contains("clash", StringComparison.OrdinalIgnoreCase);
        }

        private static IReadOnlyList<TunAdapterSnapshot> GetForeignCandidateSnapshots(
            IReadOnlyList<TunAdapterSnapshot> snapshots,
            string configuredDeviceName)
        {
            string normalizedConfiguredName = NormalizeScalar(configuredDeviceName);
            if (string.IsNullOrWhiteSpace(normalizedConfiguredName))
            {
                return Array.Empty<TunAdapterSnapshot>();
            }

            return snapshots
                .Where(snapshot => snapshot.AdapterPresent && !MatchesConfiguredName(snapshot, normalizedConfiguredName))
                .OrderBy(snapshot => GetDiscoveryRank(snapshot.DiscoverySource))
                .ThenBy(snapshot => GetAdapterConflictLabel(snapshot))
                .ToArray();
        }

        private static string GetAdapterConflictLabel(TunAdapterSnapshot snapshot)
        {
            return FirstNonEmpty(snapshot.NetConnectionId, FirstNonEmpty(snapshot.DisplayName, snapshot.Description));
        }

        private static string BuildRuntimeMessage(
            TunConfigSnapshot snapshot,
            TunAdapterSnapshot selectedAdapter,
            RouteInspectionResult routeInspection,
            MihomoFailureKind failureKind,
            string detail)
        {
            string normalizedDetail = NormalizeScalar(detail);

            return failureKind switch
            {
                MihomoFailureKind.None => "TUN adapter, routes, and DNS are healthy.",
                MihomoFailureKind.TunPermission => AppendDetail("Current process is not running with administrator privileges required for TUN.", normalizedDetail),
                MihomoFailureKind.TunDependency => AppendDetail("TUN dependencies are missing or could not be prepared.", normalizedDetail),
                MihomoFailureKind.TunAdapterMissing => AppendDetail(BuildAdapterMissingMessage(snapshot.DeviceName), normalizedDetail),
                MihomoFailureKind.TunDnsUnmanaged => AppendDetail(BuildDnsUnmanagedMessage(snapshot), normalizedDetail),
                MihomoFailureKind.TunFirewallBlocked => AppendDetail($"{BuildRouteFailureMessage(snapshot.DeviceName, routeInspection)} Windows Firewall may be blocking the '{snapshot.EffectiveStack}' stack.", normalizedDetail),
                MihomoFailureKind.TunRouteMissing => AppendDetail(BuildRouteFailureMessage(snapshot.DeviceName, routeInspection), normalizedDetail),
                _ => AppendDetail(
                    string.IsNullOrWhiteSpace(selectedAdapter.DisplayName)
                        ? "TUN runtime state is unhealthy."
                        : $"TUN runtime state for '{selectedAdapter.DisplayName}' is unhealthy.",
                    normalizedDetail),
            };
        }

        private static string BuildAdapterMissingMessage(string adapterName)
        {
            return string.IsNullOrWhiteSpace(adapterName)
                ? "TUN device object was not found."
                : $"TUN device object '{adapterName}' was not found.";
        }

        private static string BuildDnsUnmanagedMessage(TunConfigSnapshot snapshot)
        {
            var missingItems = new List<string>();
            if (!snapshot.DnsEnabled)
            {
                missingItems.Add("dns.enable");
            }

            if (!snapshot.DnsListenConfigured)
            {
                missingItems.Add("dns.listen");
            }

            if (!snapshot.DnsHijackConfigured)
            {
                missingItems.Add("tun.dns-hijack");
            }

            if (!snapshot.DnsNameserverConfigured)
            {
                missingItems.Add("dns.nameserver");
            }

            string baseMessage = "TUN routes are attached, but DNS is not managed for this profile. Website resolution may fail when system proxy is off.";
            return missingItems.Count == 0
                ? baseMessage
                : $"{baseMessage} Missing: {string.Join(", ", missingItems)}.";
        }

        private static string BuildRouteFailureMessage(string adapterName, RouteInspectionResult routeInspection)
        {
            if (!string.IsNullOrWhiteSpace(routeInspection.FailureMessage))
            {
                return routeInspection.FailureMessage;
            }

            if (!routeInspection.HasIpInterface)
            {
                return string.IsNullOrWhiteSpace(adapterName)
                    ? "TUN device object exists, but it did not appear in the IP stack."
                    : $"TUN device object '{adapterName}' exists, but it did not appear in the IP stack.";
            }

            return string.IsNullOrWhiteSpace(adapterName)
                ? "TUN device object exists and the IP interface is present, but no default route was attached."
                : $"TUN device object '{adapterName}' exists and the IP interface is present, but no default route was attached.";
        }

        private static bool IsFirewallSensitiveStack(string stack)
        {
            return stack.Equals("system", StringComparison.OrdinalIgnoreCase)
                || stack.Equals("mixed", StringComparison.OrdinalIgnoreCase);
        }

        private static bool GetDnsEnabled(YamlMappingNode root)
        {
            return TryGetChild(root, "dns", out YamlNode? dnsNode)
                && dnsNode is YamlMappingNode dnsMapping
                && GetBool(dnsMapping, "enable");
        }

        private static bool HasDnsListen(YamlMappingNode root)
        {
            return TryGetChild(root, "dns", out YamlNode? dnsNode)
                && dnsNode is YamlMappingNode dnsMapping
                && HasValue(dnsMapping, "listen");
        }

        private static bool HasDnsNameserver(YamlMappingNode root)
        {
            return TryGetChild(root, "dns", out YamlNode? dnsNode)
                && dnsNode is YamlMappingNode dnsMapping
                && HasValue(dnsMapping, "nameserver");
        }

        private static bool IsDnsAutoGenerated(string configPath)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(configPath)
                    || !string.Equals(Path.GetFileName(configPath), "runtime.yaml", StringComparison.OrdinalIgnoreCase))
                {
                    return false;
                }

                string? directory = Path.GetDirectoryName(Path.GetFullPath(configPath));
                if (string.IsNullOrWhiteSpace(directory) || !Directory.Exists(directory))
                {
                    return false;
                }

                string sourcePath = Path.Combine(directory, "source.yaml");
                string mixinPath = Path.Combine(directory, "mixin.yaml");
                return !HasDnsSection(sourcePath) && !HasDnsSection(mixinPath);
            }
            catch
            {
                return false;
            }
        }

        private static bool HasDnsSection(string path)
        {
            if (string.IsNullOrWhiteSpace(path) || !File.Exists(path))
            {
                return false;
            }

            try
            {
                var stream = new YamlStream();
                using var reader = new StringReader(File.ReadAllText(path));
                stream.Load(reader);
                return stream.Documents.Count > 0
                    && stream.Documents[0].RootNode is YamlMappingNode root
                    && TryGetChild(root, "dns", out _);
            }
            catch
            {
                return false;
            }
        }

        private static RouteInspectionResult InspectRouteAttachment(
            TunConfigSnapshot snapshot,
            AdapterDiscoveryResult discovery,
            TunAdapterSnapshot selectedAdapter,
            ulong? adapterLuid,
            uint interfaceIndex)
        {
            bool hasAnyIdentifier = adapterLuid.HasValue || interfaceIndex != 0;
            IpHelperNative.RuntimeInspectionResult inspection = IpHelperNative.InspectRuntimeInterface(adapterLuid, interfaceIndex);
            if (!inspection.IpHelperReadSucceeded)
            {
                return new RouteInspectionResult(
                    HasIpInterface: inspection.HasIpInterface,
                    RouteAttached: inspection.RouteAttached,
                    IpHelperReadSucceeded: false,
                    IpInterfaceCheckSource: inspection.IpInterfaceCheckSource,
                    RouteTableReadSource: inspection.RouteTableReadSource,
                    InteropError: inspection.InteropError,
                    Detail: hasAnyIdentifier ? string.Empty : "No interface identifier was available for IP stack inspection.",
                    FailureMessage: string.Empty,
                    IpInterfaceEntryCount: inspection.InterfaceEntryCount,
                    RouteEntryCount: inspection.RouteEntryCount,
                    ParserVersion: inspection.ParserVersion,
                    ForeignRouteInterfaces: string.Empty,
                    HasAnyForeignTunDefaultRoute: false);
            }

            string failureMessage = string.Empty;
            string detail = hasAnyIdentifier ? string.Empty : "No interface identifier was available for IP stack inspection.";
            string foreignRouteInterfaces = string.Empty;
            bool hasAnyForeignTunDefaultRoute = false;

            if (!inspection.RouteAttached && !hasAnyIdentifier)
            {
                failureMessage = string.IsNullOrWhiteSpace(snapshot.DeviceName)
                    ? "TUN device object exists, but no interface identifier was available for IP stack inspection."
                    : $"TUN device object '{snapshot.DeviceName}' exists, but no interface identifier was available for IP stack inspection.";
            }
            else if (!inspection.RouteAttached)
            {
                (failureMessage, detail, foreignRouteInterfaces, hasAnyForeignTunDefaultRoute) = ClassifyRouteFailure(
                    snapshot,
                    discovery,
                    selectedAdapter,
                    adapterLuid,
                    interfaceIndex,
                    inspection);
            }

            return new RouteInspectionResult(
                inspection.HasIpInterface,
                inspection.RouteAttached,
                inspection.IpHelperReadSucceeded,
                inspection.IpInterfaceCheckSource,
                inspection.RouteTableReadSource,
                inspection.InteropError,
                detail,
                failureMessage,
                inspection.InterfaceEntryCount,
                inspection.RouteEntryCount,
                inspection.ParserVersion,
                foreignRouteInterfaces,
                hasAnyForeignTunDefaultRoute);
        }

        private static (string FailureMessage, string Detail, string ForeignRouteInterfaces, bool HasAnyForeignTunDefaultRoute) ClassifyRouteFailure(
            TunConfigSnapshot snapshot,
            AdapterDiscoveryResult discovery,
            TunAdapterSnapshot selectedAdapter,
            ulong? adapterLuid,
            uint interfaceIndex,
            IpHelperNative.RuntimeInspectionResult inspection)
        {
            if (!inspection.HasIpInterface)
            {
                return (
                    string.IsNullOrWhiteSpace(snapshot.DeviceName)
                        ? "TUN device object exists, but it did not appear in the IP stack."
                        : $"TUN device object '{snapshot.DeviceName}' exists, but it did not appear in the IP stack.",
                    string.Empty,
                    string.Empty,
                    false);
            }

            IReadOnlyList<TunAdapterSnapshot> foreignCandidates = GetForeignCandidateSnapshots(discovery.CandidateSnapshots, snapshot.DeviceName);
            IReadOnlyList<string> foreignRouteInterfaces = FindForeignTunDefaultRouteInterfaces(
                foreignCandidates,
                inspection.RouteSnapshots,
                adapterLuid,
                interfaceIndex);

            if (foreignRouteInterfaces.Count > 0)
            {
                string foreignInterfacesText = string.Join(", ", foreignRouteInterfaces);
                string targetName = FirstNonEmpty(snapshot.DeviceName, FirstNonEmpty(selectedAdapter.NetConnectionId, selectedAdapter.DisplayName));
                string failureMessage = string.IsNullOrWhiteSpace(targetName)
                    ? $"The target TUN interface entered the IP stack, but the default route was attached to other TUN-like interface(s): {foreignInterfacesText}."
                    : $"TUN device object '{targetName}' entered the IP stack, but the default route was attached to other TUN-like interface(s): {foreignInterfacesText}.";

                return (
                    failureMessage,
                    "Detected TUN default-route ownership outside the current profile target.",
                    foreignInterfacesText,
                    true);
            }

            string adapterName = FirstNonEmpty(snapshot.DeviceName, FirstNonEmpty(selectedAdapter.NetConnectionId, selectedAdapter.DisplayName));
            string missingRouteMessage = string.IsNullOrWhiteSpace(adapterName)
                ? "The target TUN interface entered the IP stack, but no default TUN route was attached to that interface."
                : $"TUN device object '{adapterName}' entered the IP stack, but no default TUN route was attached to that interface.";

            return (
                missingRouteMessage,
                "The target interface is present in the IP stack, but no default or split-default TUN route was found on that interface.",
                string.Empty,
                false);
        }

        private static IReadOnlyList<string> FindForeignTunDefaultRouteInterfaces(
            IReadOnlyList<TunAdapterSnapshot> foreignCandidates,
            IReadOnlyList<IpHelperNative.IpRouteSnapshot> routeSnapshots,
            ulong? targetLuid,
            uint targetInterfaceIndex)
        {
            if (foreignCandidates.Count == 0 || routeSnapshots.Count == 0)
            {
                return Array.Empty<string>();
            }

            return foreignCandidates
                .Where(candidate => HasDefaultRouteAttachment(routeSnapshots, candidate.InterfaceIndex, targetLuid, targetInterfaceIndex))
                .Select(GetAdapterConflictLabel)
                .Where(name => !string.IsNullOrWhiteSpace(name))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToArray();
        }

        private static bool HasDefaultRouteAttachment(
            IReadOnlyList<IpHelperNative.IpRouteSnapshot> routeSnapshots,
            uint candidateInterfaceIndex,
            ulong? targetLuid,
            uint targetInterfaceIndex)
        {
            if (candidateInterfaceIndex == 0)
            {
                return false;
            }

            bool hasIpv4Default = false;
            bool hasIpv4LowerHalf = false;
            bool hasIpv4UpperHalf = false;
            bool hasIpv6Default = false;
            bool hasIpv6LowerHalf = false;
            bool hasIpv6UpperHalf = false;

            foreach (IpHelperNative.IpRouteSnapshot routeSnapshot in routeSnapshots)
            {
                if (routeSnapshot.InterfaceIndex != candidateInterfaceIndex
                    || (targetLuid.HasValue && routeSnapshot.InterfaceLuid == targetLuid.Value)
                    || (targetInterfaceIndex != 0 && routeSnapshot.InterfaceIndex == targetInterfaceIndex))
                {
                    continue;
                }

                switch (routeSnapshot.AddressFamily)
                {
                    case IpHelperNative.AddressFamilyInet:
                        if (routeSnapshot.PrefixLength == 0 && routeSnapshot.Ipv4Address == 0)
                        {
                            hasIpv4Default = true;
                            break;
                        }

                        if (routeSnapshot.PrefixLength == 1)
                        {
                            if (routeSnapshot.Ipv4Address == 0)
                            {
                                hasIpv4LowerHalf = true;
                            }
                            else if (routeSnapshot.Ipv4Address == 0x00000080)
                            {
                                hasIpv4UpperHalf = true;
                            }
                        }

                        break;

                    case IpHelperNative.AddressFamilyInet6:
                        if (routeSnapshot.PrefixLength == 0 && routeSnapshot.Ipv6Address.IsZero)
                        {
                            hasIpv6Default = true;
                            break;
                        }

                        if (routeSnapshot.PrefixLength == 1)
                        {
                            if (routeSnapshot.Ipv6Address.IsZero)
                            {
                                hasIpv6LowerHalf = true;
                            }
                            else if (routeSnapshot.Ipv6Address.IsUpperHalfSplitDefault)
                            {
                                hasIpv6UpperHalf = true;
                            }
                        }

                        break;
                }
            }

            return hasIpv4Default
                || (hasIpv4LowerHalf && hasIpv4UpperHalf)
                || hasIpv6Default
                || (hasIpv6LowerHalf && hasIpv6UpperHalf);
        }

        private void LogRuntimeDiagnosticsIfChanged(
            TunConfigSnapshot snapshot,
            AdapterDiscoveryResult discovery,
            TunAdapterSnapshot selectedAdapter,
            ulong? adapterLuid,
            uint interfaceIndex,
            RouteInspectionResult routeInspection,
            TunRuntimeStatus runtimeStatus)
        {
            IReadOnlyList<string> foreignCandidateNames = GetForeignCandidateSnapshots(discovery.CandidateSnapshots, snapshot.DeviceName)
                .Select(GetAdapterConflictLabel)
                .Where(name => !string.IsNullOrWhiteSpace(name))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToArray();
            IReadOnlyList<string> thirdPartyConflictHints = GetThirdPartyTunConflictHints();

            string fingerprint = string.Join(
                " | ",
                new[]
                {
                    $"tun.device={FormatDiagnosticValue(snapshot.DeviceName)}",
                    $"attemptedOpenNames={FormatDiagnosticList(discovery.AttemptedOpenNames)}",
                    $"candidates={FormatDiagnosticCandidates(discovery.CandidateSnapshots)}",
                    $"targetAdapterPresent={discovery.TargetAdapterPresent}",
                    $"foreignCandidates={FormatDiagnosticList(foreignCandidateNames)}",
                    $"thirdPartyConflicts={FormatDiagnosticList(thirdPartyConflictHints)}",
                    $"selectedAdapter={FormatDiagnosticValue(selectedAdapter.DisplayName)}",
                    $"selectedInterfaceIndex={interfaceIndex}",
                    $"selectedLuid={(adapterLuid.HasValue ? $"0x{adapterLuid.Value:X}" : "<none>")}",
                    $"ipHelperReadSucceeded={routeInspection.IpHelperReadSucceeded}",
                    $"ipHelperParser={FormatDiagnosticValue(routeInspection.ParserVersion)}",
                    $"ipInterfaceEntryCount={routeInspection.IpInterfaceEntryCount}",
                    $"routeEntryCount={routeInspection.RouteEntryCount}",
                    $"hasIpInterface={routeInspection.HasIpInterface}",
                    $"routeAttached={routeInspection.RouteAttached}",
                    $"dnsHijackConfigured={snapshot.DnsHijackConfigured}",
                    $"dnsManaged={snapshot.DnsManaged}",
                    $"dnsAutoGenerated={snapshot.DnsAutoGenerated}",
                    $"foreignRouteInterfaces={FormatDiagnosticValue(routeInspection.ForeignRouteInterfaces)}",
                    $"ipInterfaceCheckSource={FormatDiagnosticValue(routeInspection.IpInterfaceCheckSource)}",
                    $"routeTableReadSource={FormatDiagnosticValue(routeInspection.RouteTableReadSource)}",
                    $"interopError={FormatDiagnosticValue(routeInspection.InteropError)}",
                    $"routeFailureMessage={FormatDiagnosticValue(routeInspection.FailureMessage)}",
                    $"failureKind={runtimeStatus.FailureKind}",
                    $"message={FormatDiagnosticValue(runtimeStatus.Message)}",
                });

            lock (_diagnosticGate)
            {
                if (string.Equals(_lastRuntimeDiagnosticFingerprint, fingerprint, StringComparison.Ordinal))
                {
                    return;
                }

                _lastRuntimeDiagnosticFingerprint = fingerprint;
            }

            _logService.Add($"[WARNING] TUN runtime diagnostics: {fingerprint}", LogLevel.Warning);
        }

        private void ResetRuntimeDiagnostics()
        {
            lock (_diagnosticGate)
            {
                _lastRuntimeDiagnosticFingerprint = string.Empty;
            }
        }

        private static bool LooksLikeTunAdapter(string name, string description, string extraName)
        {
            return ContainsTunKeyword(name)
                || ContainsTunKeyword(description)
                || ContainsTunKeyword(extraName);
        }

        private static bool ContainsTunKeyword(string value)
        {
            string normalized = NormalizeScalar(value);
            return normalized.Contains("wintun", StringComparison.OrdinalIgnoreCase)
                || normalized.Contains("wireguard", StringComparison.OrdinalIgnoreCase)
                || normalized.Contains("mihomo", StringComparison.OrdinalIgnoreCase)
                || normalized.Contains("clash", StringComparison.OrdinalIgnoreCase);
        }

        private static uint ReadUInt32(object? value)
        {
            return value switch
            {
                uint unsigned => unsigned,
                int signed when signed > 0 => (uint)signed,
                ushort shortUnsigned => shortUnsigned,
                short shortSigned when shortSigned > 0 => (uint)shortSigned,
                long longSigned when longSigned > 0 => (uint)longSigned,
                string text when uint.TryParse(text, out uint parsed) => parsed,
                _ => 0,
            };
        }

        private static void AddAttemptedName(List<string> attemptedNames, string candidateName)
        {
            if (string.IsNullOrWhiteSpace(candidateName))
            {
                return;
            }

            if (!attemptedNames.Contains(candidateName, StringComparer.OrdinalIgnoreCase))
            {
                attemptedNames.Add(candidateName);
            }
        }

        private static void TrySetFirstDetail(ref string target, string candidate)
        {
            if (string.IsNullOrWhiteSpace(target) && !string.IsNullOrWhiteSpace(candidate))
            {
                target = candidate;
            }
        }

        private static string FirstNonEmpty(string left, string right)
        {
            return !string.IsNullOrWhiteSpace(left) ? left : right;
        }

        private static string MergeDiscoverySource(string left, string right)
        {
            if (string.IsNullOrWhiteSpace(left))
            {
                return right;
            }

            if (string.IsNullOrWhiteSpace(right) || left.Contains(right, StringComparison.OrdinalIgnoreCase))
            {
                return left;
            }

            return $"{left},{right}";
        }

        private static string CombineDetails(params string[] parts)
        {
            return string.Join(
                " ",
                parts
                    .Select(NormalizeScalar)
                    .Where(part => !string.IsNullOrWhiteSpace(part)));
        }

        private static string FormatDiagnosticValue(string value)
        {
            return string.IsNullOrWhiteSpace(value) ? "<empty>" : $"'{value}'";
        }

        private static string FormatDiagnosticList(IReadOnlyList<string> values)
        {
            return values.Count == 0
                ? "[]"
                : "[" + string.Join(", ", values.Select(FormatDiagnosticValue)) + "]";
        }

        private static string FormatDiagnosticCandidates(IReadOnlyList<TunAdapterSnapshot> snapshots)
        {
            if (snapshots.Count == 0)
            {
                return "[]";
            }

            string[] items = snapshots
                .Select(snapshot =>
                    "{"
                    + $"DisplayName={FormatDiagnosticValue(snapshot.DisplayName)}, "
                    + $"NetConnectionId={FormatDiagnosticValue(snapshot.NetConnectionId)}, "
                    + $"InterfaceIndex={snapshot.InterfaceIndex}, "
                    + $"AdapterPresent={snapshot.AdapterPresent}, "
                    + $"CanOpenByWintunApi={snapshot.CanOpenByWintunApi}, "
                    + $"OpenError={FormatDiagnosticValue(snapshot.OpenError)}, "
                    + $"DiscoverySource={FormatDiagnosticValue(snapshot.DiscoverySource)}"
                    + "}")
                .ToArray();

            return "[" + string.Join("; ", items) + "]";
        }

        private static string ResolveWintunSourcePath()
        {
            string relativePath = RuntimeInformation.ProcessArchitecture switch
            {
                Architecture.X64 => Path.Combine("Tun", "x86_64", WintunFileName),
                Architecture.Arm64 => Path.Combine("Tun", "ARM64", WintunFileName),
                _ => throw new PlatformNotSupportedException($"Unsupported architecture: {RuntimeInformation.ProcessArchitecture}"),
            };

            return Path.Combine(AppContext.BaseDirectory, relativePath);
        }

        private static string ResolveWintunTargetPath(string kernelExecutablePath)
        {
            string kernelDirectory = Path.GetDirectoryName(Path.GetFullPath(kernelExecutablePath))
                ?? throw new InvalidOperationException("Kernel executable directory is invalid.");
            return Path.Combine(kernelDirectory, WintunFileName);
        }

        private static TunPreparationResult CreateFailure(MihomoFailureKind failureKind, string message)
        {
            return new TunPreparationResult
            {
                Success = false,
                FailureKind = failureKind,
                Message = message,
            };
        }

        private static string FormatDriverVersion(uint rawVersion)
        {
            if (rawVersion == 0)
            {
                return string.Empty;
            }

            uint major = (rawVersion >> 16) & 0xFFFF;
            uint minor = rawVersion & 0xFFFF;
            return $"{major}.{minor}";
        }

        private static bool TryGetChild(YamlMappingNode mapping, string key, out YamlNode? value)
        {
            foreach (var pair in mapping.Children)
            {
                if (string.Equals((pair.Key as YamlScalarNode)?.Value, key, StringComparison.OrdinalIgnoreCase))
                {
                    value = pair.Value;
                    return true;
                }
            }

            value = null;
            return false;
        }

        private static bool GetBool(YamlMappingNode mapping, string key)
        {
            return bool.TryParse(GetString(mapping, key), out bool result) && result;
        }

        private static string GetString(YamlMappingNode mapping, string key)
        {
            if (!TryGetChild(mapping, key, out YamlNode? value))
            {
                return string.Empty;
            }

            return value switch
            {
                YamlScalarNode scalar => NormalizeScalar(scalar.Value),
                _ => string.Empty,
            };
        }

        private static bool HasValue(YamlMappingNode mapping, string key)
        {
            if (!TryGetChild(mapping, key, out YamlNode? value) || value is null)
            {
                return false;
            }

            return value switch
            {
                YamlScalarNode scalar => !string.IsNullOrWhiteSpace(scalar.Value),
                YamlSequenceNode sequence => sequence.Children.Count > 0,
                _ => true,
            };
        }

        private static string NormalizeScalar(string? value)
        {
            return value?.Trim() ?? string.Empty;
        }

        private static string AppendDetail(string message, string detail)
        {
            return string.IsNullOrWhiteSpace(detail)
                ? message
                : $"{message} {detail}";
        }

        private readonly record struct TunConfigSnapshot(
            bool IsEnabled,
            string Stack,
            string DeviceName,
            bool DnsHijackConfigured,
            bool DnsEnabled,
            bool DnsListenConfigured,
            bool DnsNameserverConfigured,
            bool DnsAutoGenerated)
        {
            public static TunConfigSnapshot Disabled => new(false, string.Empty, string.Empty, false, false, false, false, false);

            public string EffectiveStack => string.IsNullOrWhiteSpace(Stack) ? "system" : Stack;

            public bool DnsManaged => DnsEnabled && DnsListenConfigured && DnsHijackConfigured && DnsNameserverConfigured;
        }

        private readonly record struct TunAdapterSnapshot(
            string DisplayName,
            string Description,
            string NetConnectionId,
            uint InterfaceIndex,
            bool AdapterPresent,
            bool CanOpenByWintunApi,
            string OpenError,
            string DiscoverySource)
        {
            public static TunAdapterSnapshot Empty => new(
                string.Empty,
                string.Empty,
                string.Empty,
                0,
                false,
                false,
                string.Empty,
                string.Empty);
        }

        private readonly record struct RouteInspectionResult(
            bool HasIpInterface,
            bool RouteAttached,
            bool IpHelperReadSucceeded,
            string IpInterfaceCheckSource,
            string RouteTableReadSource,
            string InteropError,
            string Detail,
            string FailureMessage,
            int IpInterfaceEntryCount,
            int RouteEntryCount,
            string ParserVersion,
            string ForeignRouteInterfaces,
            bool HasAnyForeignTunDefaultRoute)
        {
            public static RouteInspectionResult Empty => new(
                false,
                false,
                false,
                "NotRun",
                "NotRun",
                string.Empty,
                string.Empty,
                string.Empty,
                0,
                0,
                string.Empty,
                string.Empty,
                false);
        }

        private sealed class AdapterDiscoveryResult : IDisposable
        {
            public AdapterDiscoveryResult(
                string configuredDeviceName,
                WintunNative.AdapterHandle? adapterHandle,
                TunAdapterSnapshot selectedSnapshot,
                IReadOnlyList<string> attemptedOpenNames,
                IReadOnlyList<TunAdapterSnapshot> candidateSnapshots,
                string primaryOpenError)
            {
                ConfiguredDeviceName = configuredDeviceName;
                AdapterHandle = adapterHandle;
                SelectedSnapshot = selectedSnapshot;
                AttemptedOpenNames = attemptedOpenNames;
                CandidateSnapshots = candidateSnapshots;
                PrimaryOpenError = primaryOpenError;
            }

            public string ConfiguredDeviceName { get; }

            public WintunNative.AdapterHandle? AdapterHandle { get; }

            public TunAdapterSnapshot SelectedSnapshot { get; }

            public IReadOnlyList<string> AttemptedOpenNames { get; }

            public IReadOnlyList<TunAdapterSnapshot> CandidateSnapshots { get; }

            public string PrimaryOpenError { get; }

            public bool TargetAdapterPresent => AdapterHandle is not null || SelectedSnapshot.AdapterPresent;

            public void Dispose()
            {
                AdapterHandle?.Dispose();
            }
        }
    }
}
