namespace ClashWinUI.Models
{
    public sealed class TunRuntimeStatus
    {
        public required bool IsConfigured { get; init; }

        public required bool IsHealthy { get; init; }

        public required bool DriverLoaded { get; init; }

        public required string DriverVersion { get; init; }

        public required bool AdapterPresent { get; init; }

        public required string AdapterName { get; init; }

        public required bool RouteAttached { get; init; }

        public required string EffectiveStack { get; init; }

        public required bool FirewallEnabled { get; init; }

        public required bool DnsHijackConfigured { get; init; }

        public required bool DnsManaged { get; init; }

        public required bool DnsAutoGenerated { get; init; }

        public required MihomoFailureKind FailureKind { get; init; }

        public required string Message { get; init; }

        public static TunRuntimeStatus Disabled()
        {
            return new TunRuntimeStatus
            {
                IsConfigured = false,
                IsHealthy = false,
                DriverLoaded = false,
                DriverVersion = string.Empty,
                AdapterPresent = false,
                AdapterName = string.Empty,
                RouteAttached = false,
                EffectiveStack = string.Empty,
                FirewallEnabled = false,
                DnsHijackConfigured = false,
                DnsManaged = false,
                DnsAutoGenerated = false,
                FailureKind = MihomoFailureKind.None,
                Message = string.Empty,
            };
        }
    }
}
